package project;

public enum UnitAmenities {
	CENTRALAIR, CERAMICTYLING, CITYVIEW, DISHWASHER, EXTRASTORAGE, FIREPLACE, FURNISHED, GRADENVIEW, LOFT, PRIVATEOUTDOORSPACE, WASGERDRYER, WOODFLOORING
}
